### ISSUE TITLE
BaseModel.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-doladosu/potatoorm#2]
``` php

namespace Dara\Origins;
use PDO;
use Dotenv;

```

Imports should be from shortest to longest

**Comment by unicodeveloper** [comment]
``` php

    public function __construct()
    {
        $this->loadEnv();
        $this->connection = new Connection($_ENV['P_DRIVER'], $_ENV['P_HOST'], $_ENV['P_DBNAME'], $_ENV['P_USER'], $_ENV['P_PASS']);
        $this->className = get_called_class();
    }
```

You used the `$_ENV` Superglobal array which is awesome, but how does the developer pass those values when using the package so it can be accessible from the $_ENV array by your method?

**Comment by unicodeveloper** [comment]
In this case, it's preferable you create your custom Exceptions and throw exceptions when something goes wrong than just returning the error message in a string.

`destroy`, `updateRow`, `insertRow`

**Comment by dara-tobi** [comment]
I've updated the constructor of the class to look in the root directory of the current project for the .env file, and that info is now reflected in the `readme` of the package.

**Comment by dara-tobi** [comment]
The mentioned functions have been updated to throw exceptions.
