### ISSUE TITLE
Loading Dotenv in BaseModelHelper.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-doladosu/potatoorm#6]
``` php
    /**
     * Load environment variables
     * 
     * @return null
     */
    public function loadEnv()
    {
        $dotenv = new Dotenv\Dotenv($this->envDirectory);
        $dotenv->load();
    }
```

You already did `use Dotenv` at the top which should have been `use Dotenv\Dotenv`, so you should just have `$dotenv = new Dotenv($this->envDirectory)`

**Comment by dara-tobi** [comment]
Alright. I've fixed this.

**Comment by unicodeveloper** [comment]
You haven't fixed anything. I just checked it now
<img width="495" alt="screen shot 2015-10-16 at 11 06 12 am" src="https://cloud.githubusercontent.com/assets/2946769/10539217/fbfc9c74-73f5-11e5-9282-49d03975dfb1.png">
