### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by unicodeveloper** [andela-doladosu/potatoorm#7]
Why is your build failing?

**Comment by dara-tobi** [comment]
This is because the constructor of my BaseModel class needs a `.env` file. And the file is not being located on travis.

**Comment by unicodeveloper** [comment]
You can put environment variables on Travis. Check the settings tab. Didn't you guys see when I did it for Chopbox?

**Comment by dara-tobi** [comment]
I tried that already. The `dotenv` package requires the actual `.env` file to be readable.

**Comment by dara-tobi** [comment]
I'm getting this on travis

![snip20151016_2](https://cloud.githubusercontent.com/assets/8155075/10539332/c5b1d390-73f6-11e5-9fda-f60e81b2c24f.png)

**Comment by unicodeveloper** [comment]
Have you tried doing something like this: 

//optionally specify a list of environments, for example to test different RDBMS
env:
- DB=mysql
- DB=pgsql

Adding it from the .travis.yml file

**Comment by dara-tobi** [comment]
I have:
- -DB=mysql

**Comment by unicodeveloper** [comment]
Just that?..What of the remaining env variables?

**Comment by dara-tobi** [comment]
Not anymore. I have put in all the variables. It's still failing.

**Comment by unicodeveloper** [comment]
I guess you would have to use the `getenv` function instead of the $_ENV you used

Then delete the `.env` file or rename it to `.env.example`
